/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job;

/**
 *
 * @author giann
 */
public class HRTeamMember extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HRTeamMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JLabel();
        cal = new javax.swing.JLabel();
        app = new javax.swing.JLabel();
        cand = new javax.swing.JLabel();
        jobs = new javax.swing.JLabel();
        empl = new javax.swing.JLabel();
        signin4 = new javax.swing.JLabel();
        insjob = new javax.swing.JLabel();
        hr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setText(" ");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 110, 30));

        cal.setText(" ");
        cal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calMouseClicked(evt);
            }
        });
        getContentPane().add(cal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 110, 30));

        app.setText(" ");
        app.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appMouseClicked(evt);
            }
        });
        getContentPane().add(app, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 130, 30));

        cand.setText(" ");
        cand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                candMouseClicked(evt);
            }
        });
        getContentPane().add(cand, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 120, 30));

        jobs.setText(" ");
        jobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobsMouseClicked(evt);
            }
        });
        getContentPane().add(jobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 90, 30));

        empl.setText(" ");
        empl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emplMouseClicked(evt);
            }
        });
        getContentPane().add(empl, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 120, 30));

        signin4.setText(" ");
        signin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signin4MouseClicked(evt);
            }
        });
        getContentPane().add(signin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, 30));

        insjob.setText(" ");
        insjob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insjobMouseClicked(evt);
            }
        });
        getContentPane().add(insjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, 30));

        hr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/HR Team Member.jpg"))); // NOI18N
        hr.setText(" ");
        getContentPane().add(hr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calMouseClicked
           
    }//GEN-LAST:event_calMouseClicked

    private void appMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appMouseClicked
       
            ;
    }//GEN-LAST:event_appMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
         Home a = new Home();
            a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void candMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_candMouseClicked

    private void jobsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jobsMouseClicked

    private void emplMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emplMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emplMouseClicked

    private void signin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signin4MouseClicked

    private void insjobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insjobMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_insjobMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRTeamMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRTeamMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRTeamMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRTeamMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRTeamMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel app;
    private javax.swing.JLabel cal;
    private javax.swing.JLabel cand;
    private javax.swing.JLabel empl;
    private javax.swing.JLabel hr;
    private javax.swing.JLabel insjob;
    private javax.swing.JLabel jobs;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel signin4;
    // End of variables declaration//GEN-END:variables
}
